version: 2

shared:
  test: &shared_test
    working_directory: ~/zengin-py
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init
            git submodule foreach 'git pull origin master'
      - run:
          command: sudo pip install -U pip setuptools tox wheel twine
      - run:
          command: tox -e $TOX_ENV

jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/zengin-py
    steps:
      - checkout
      - run:
          command: |
            git submodule update --init
            git submodule foreach 'git pull origin master'
      - run:
          command: sudo pip install -U pip setuptools tox wheel twine

  test_3_4:
    <<: *shared_test
    docker:
      - image: circleci/python:3.4
    environment:
      TOX_ENV: py34
  test_3_5:
    <<: *shared_test
    docker:
      - image: circleci/python:3.5
    environment:
      TOX_ENV: py35
  test_3_6:
    <<: *shared_test
    docker:
      - image: circleci/python:3.6
    environment:
      TOX_ENV: py36
  test_3_7:
    <<: *shared_test
    docker:
      - image: circleci/python:3.7
    environment:
      TOX_ENV: py37
  test_flake8:
    <<: *shared_test
    docker:
      - image: circleci/python:latest
    environment:
      TOX_ENV: flake8

workflows:
  version: 2
  build:
    jobs:
      - test_3_4
      - test_3_5
      - test_3_6
      - test_3_7
      - test_flake8
      - build:
          requires:
            - test_3_4
            - test_3_5
            - test_3_6
            - test_3_7
            - test_flake8
          filters:
            branches:
              only: master

